version: '2'

services:
    opac-airflow:
        build:
            context: ./airflow
        ports:
          - "8080:8080"
        command: webserver
        environment:
          - AIRFLOW_HOME=/usr/local/airflow
          - KERNEL_URL=${KERNEL_URL}
          - OPAC_MONGODB_NAME = ${OPAC_MONGODB_NAME}
          - OPAC_MONGODB_HOSTNAME = ${OPAC_MONGODB_HOSTNAME}
          - OPAC_MONGODB_USERNAME = ${OPAC_MONGODB_USERNAME}
          - OPAC_MONGODB_PASS = ${OPAC_MONGODB_PASS}
